const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const state={forceImage:false,hasAttachment:false,configured:false,busy:false};
const els={clearBtn:$('#clearBtn'),settingsBtn:$('#settingsBtn'),apiStatus:$('#apiStatus'),modeTitle:$('#modeTitle'),chatArea:$('#chatArea'),emptyState:$('#emptyState'),messages:$('#messages'),loadingBar:$('#loadingBar'),attachmentPreview:$('#attachmentPreview'),attachmentName:$('#attachmentName'),removeAttachment:$('#removeAttachment'),attachBtn:$('#attachBtn'),drawBtn:$('#drawBtn'),promptInput:$('#promptInput'),sendBtn:$('#sendBtn'),dialog:$('#settingsDialog'),openSettingsFromEmpty:$('#openSettingsFromEmpty'),saveSettingsBtn:$('#saveSettingsBtn'),apiKeyInput:$('#apiKeyInput'),baseUrlInput:$('#baseUrlInput'),chatModelInput:$('#chatModelInput'),imageModelInput:$('#imageModelInput'),toast:$('#toast')};
function boot(){loadSettings();bindEvents();updateModeUI();autosizeTextarea()}
function bindEvents(){els.settingsBtn.addEventListener('click',openSettings);els.openSettingsFromEmpty.addEventListener('click',openSettings);els.apiStatus.addEventListener('click',openSettings);els.clearBtn.addEventListener('click',()=>{if(!els.messages.children.length)return;if(confirm('确定要清空当前所有聊天记录吗？')){els.messages.innerHTML='';syncEmptyState();toast('已清空对话')}});els.drawBtn.addEventListener('click',()=>{if(state.hasAttachment)return;state.forceImage=!state.forceImage;updateModeUI()});els.attachBtn.addEventListener('click',()=>{state.hasAttachment=true;state.forceImage=false;els.attachmentName.textContent=`preview-${Math.floor(Math.random()*900+100)}.png`;updateModeUI();toast('已模拟选择图片，可输入“分析这张图片”')});els.removeAttachment.addEventListener('click',()=>{state.hasAttachment=false;updateModeUI()});els.sendBtn.addEventListener('click',sendMessage);els.promptInput.addEventListener('keydown',(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});els.promptInput.addEventListener('input',autosizeTextarea);$$('.quick-card').forEach((b)=>{b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='chat'){state.forceImage=false;els.promptInput.value='';toast('已切换为普通聊天')}if(a==='image'){state.forceImage=true;els.promptInput.focus();toast('画图模式已开启，下一条会生成图片')}if(a==='vision'){state.hasAttachment=true;state.forceImage=false;els.attachmentName.textContent=`vision-sample-${Math.floor(Math.random()*90+10)}.jpg`;toast('已模拟上传图片')}updateModeUI()})});$$('.suggestion').forEach((b)=>{b.addEventListener('click',()=>{els.promptInput.value=b.textContent.replace('↖ ','').trim();autosizeTextarea();els.promptInput.focus()})});els.saveSettingsBtn.addEventListener('click',(e)=>{e.preventDefault();saveSettings()})}
function looksLikeImageRequest(text){const n=text.trim().toLowerCase();if(!n)return false;const p=['/image','/img','/draw','画图','绘图','生图','生成图片','生成一张','帮我画','画一张','做一张图','出一张图','create an image','generate an image','draw '];if(p.some(x=>n.startsWith(x)))return true;const iw=['图片','图像','插画','海报','头像','壁纸','logo','poster','illustration','wallpaper'];const aw=['生成','画','绘制','设计','create','generate','draw','design'];return iw.some(w=>n.includes(w))&&aw.some(w=>n.includes(w))}
function cleanImagePrompt(text){let prompt=text.trim();const prefixes=['/image','/img','/draw','画图','绘图','生图','生成图片'];for(const prefix of prefixes){if(prompt.toLowerCase().startsWith(prefix.toLowerCase())){prompt=prompt.slice(prefix.length).trimStart();if(prompt.startsWith(':')||prompt.startsWith('：'))prompt=prompt.slice(1).trimStart();break}}return prompt||text.trim()}
async function sendMessage(){if(state.busy)return;const raw=els.promptInput.value.trim();if(!raw&&!state.hasAttachment)return;const wasAttachment=state.hasAttachment;const shouldImage=!wasAttachment&&(state.forceImage||looksLikeImageRequest(raw));const content=shouldImage?cleanImagePrompt(raw):(raw||'分析这张图片');addMessage('user',content,{attachment:wasAttachment?els.attachmentName.textContent:null});els.promptInput.value='';state.forceImage=false;state.hasAttachment=false;state.busy=true;updateModeUI();autosizeTextarea();setLoading(true);if(shouldImage){const loading=addMessage('assistant','正在根据你的描述生成图片…');await wait(900);loading.remove();addImageMessage(content)}else{const reply=wasAttachment?'我已收到图片，可以帮你分析主体、构图、风格、颜色和可改进的地方。':makeDemoReply(content);await typeAssistant(reply)}state.busy=false;setLoading(false)}
function makeDemoReply(input){if(/api|key|设置|配置/i.test(input))return '你可以点击右上角 ⚙ 或顶部状态胶囊打开 API 设置。这里是静态预览，所以只会保存到浏览器 localStorage。';if(/短视频|脚本/.test(input))return '当然。示例脚本：\n\n**开头 3 秒**：用强钩子提出问题。\n**中段**：给出 3 个清晰步骤。\n**结尾**：引导评论或收藏。';return `这是网页版预览回复：\n\n你刚才输入的是「${input}」。\n\n正式 Flutter App 中，这里会调用配置的聊天模型，并以流式打字效果展示回答。`}
function addMessage(role,content,options={}){syncEmptyState(false);const row=document.createElement('div');row.className=`message-row ${role}`;const avatar=document.createElement('div');avatar.className='avatar';avatar.textContent=role==='user'?'👤':'✦';const bubble=document.createElement('div');bubble.className='bubble';bubble.textContent=content;if(options.attachment){const chip=document.createElement('div');chip.style.cssText='margin-top:10px;padding:7px 10px;border-radius:999px;background:rgba(255,255,255,.10);font-size:12px;color:#f8fafc;display:inline-block;';chip.textContent=`🖼 ${options.attachment}`;bubble.appendChild(chip)}if(role==='assistant')row.append(avatar,bubble);else row.append(bubble,avatar);els.messages.appendChild(row);scrollToBottom();return row}
function addImageMessage(prompt){syncEmptyState(false);const row=document.createElement('div');row.className='message-row assistant';row.innerHTML=`<div class="avatar">✦</div><div class="bubble image-card"><div class="fake-image">AI Image Preview<br><small>${escapeHtml(prompt)}</small></div><button class="save-btn">⬇ 保存到相册</button></div>`;row.querySelector('.save-btn').addEventListener('click',()=>toast('静态预览：这里会保存生成图片'));els.messages.appendChild(row);scrollToBottom()}
async function typeAssistant(text){const row=addMessage('assistant','');const bubble=row.querySelector('.bubble');for(const char of text){bubble.textContent+=char;scrollToBottom();await wait(12)}}
function syncEmptyState(forceEmpty){const empty=forceEmpty??els.messages.children.length===0;els.emptyState.hidden=!empty;els.messages.hidden=empty}
function updateModeUI(){els.modeTitle.textContent=state.forceImage?'画图模式已开启，下一条将生成图片':'聊天与生图已合并，像聊天一样创作';els.drawBtn.classList.toggle('active',state.forceImage);els.promptInput.classList.toggle('image-mode',state.forceImage);els.promptInput.placeholder=state.forceImage?'描述你想生成的图片...':'输入消息，或说“画一张…”';els.attachmentPreview.hidden=!state.hasAttachment;els.drawBtn.disabled=state.hasAttachment;els.drawBtn.style.opacity=state.hasAttachment?'.45':'1'}
function setLoading(loading){els.loadingBar.hidden=!loading;els.sendBtn.classList.toggle('loading',loading);els.sendBtn.textContent=loading?'⌛':'↑'}
function autosizeTextarea(){els.promptInput.style.height='auto';els.promptInput.style.height=Math.min(els.promptInput.scrollHeight,138)+'px'}
function openSettings(){if(typeof els.dialog.showModal==='function')els.dialog.showModal();else alert('当前浏览器不支持 dialog 标签，请换用较新的浏览器。')}
function loadSettings(){const saved=JSON.parse(localStorage.getItem('luna_preview_settings')||'{}');els.apiKeyInput.value=saved.apiKey||'';els.baseUrlInput.value=saved.baseUrl||'https://api.openai.com/v1';els.chatModelInput.value=saved.chatModel||'gpt-4o-mini';els.imageModelInput.value=saved.imageModel||'dall-e-3';state.configured=Boolean(saved.apiKey);updateApiStatus()}
function saveSettings(){const data={apiKey:els.apiKeyInput.value.trim(),baseUrl:els.baseUrlInput.value.trim()||'https://api.openai.com/v1',chatModel:els.chatModelInput.value.trim()||'gpt-4o-mini',imageModel:els.imageModelInput.value.trim()||'dall-e-3'};localStorage.setItem('luna_preview_settings',JSON.stringify(data));state.configured=Boolean(data.apiKey);updateApiStatus();els.dialog.close();toast('设置已保存')}
function updateApiStatus(){els.apiStatus.className=`status-pill ${state.configured?'ok':'warning'}`;els.apiStatus.textContent=state.configured?'✅ 已配置':'🔑 未配置'}
function toast(message){els.toast.textContent=message;els.toast.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>{els.toast.hidden=true},1800)}
function scrollToBottom(){requestAnimationFrame(()=>{els.chatArea.scrollTop=els.chatArea.scrollHeight})}
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function escapeHtml(text){return text.replace(/[&<>'"]/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
boot();
